Init repository architecture and API
BaseAdresseNationale/id-fix pull request #1
Opened 2023-04-19 16:12 UTC by antoineludeau

Context : repository initialization. Please see README.md (or LISEZ-MOI.md) for more info.

2023-04-19 17:10 UTC, nkokla requested changes

2023-04-19 17:10 UTC, nkokla commented on src/app.ts
> +app.use(bodyParser.json());
Il y a encore besoin du BodyParser ? 
Il me semble qu'il n'est plus nécéssaire depuis Express 4.16.x (https://stackoverflow.com/a/47232318/8784518)
(De plus, il ne semble pas présent au sein des dépendances du `package.json` 😜)

2023-04-19 17:10 UTC, nkokla commented on src/routes.ts
> +router.post("/id-fix", authMiddleware, (req: Request, res: Response) => {
`.post` ? 😜

2023-04-19 17:10 UTC, nkokla commented on src/utils.ts
> +  const authorizedTokens = (process.env.IDEFIX_ADMIN_TOKENS || "")
Il ne manque pas un fichier `.env.sample` ?

2023-04-20 13:40 UTC, antoineludeau commented on LICENSE
> +MIT License
On garde MIT pour le moment et on pourra changer ensuite.

2023-04-21 12:20 UTC, nkokla approved these changes
Juste une remarque super light, mais pas indispensable. C'est good pour moi ! 👍

2023-04-24 08:19 UTC, merged